# do not install anything extra onto the image
language: generic

# use a Mac OSX image
os: osx

# run the script to download and install Unity editor
install:
- sudo -E sh ./scripts/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./scripts/build.sh

env:
  global:
  - UNITYCI_PROJECT_NAME="OpenTibia"